# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-26 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', '查看用户'), ('edit_user', '管理用户')), 'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
    ]
